use crate::state::{OptimizationProfile, ProjectWithLaunchScript};
use std::fs;
use std::path::Path;

const SCRIPT_HEADER: &str = "# Generated by SkillVault Desktop Claude Optimizer";

/// Check if a project has a SkillVault-generated launch script
pub fn has_launch_script(project_path: &Path) -> bool {
    let script_path = project_path.join("start-claude.sh");
    if !script_path.exists() {
        return false;
    }
    // Check if it was generated by us
    if let Ok(content) = fs::read_to_string(&script_path) {
        content.contains(SCRIPT_HEADER)
    } else {
        false
    }
}

/// Check if a start-claude.sh exists (regardless of origin)
pub fn script_exists(project_path: &Path) -> bool {
    project_path.join("start-claude.sh").exists()
}

/// Generate the launch script content
pub fn generate_script(project_name: &str, profile: &OptimizationProfile) -> String {
    let env_inline = super::profile::build_env_inline(profile);
    // Sanitize project_name: strip newlines to prevent shell injection
    let safe_name = project_name.replace('\n', " ").replace('\r', " ");

    let mut cli_parts = Vec::new();
    if profile.skip_permissions && !profile.extra_cli_args.contains("--dangerously-skip-permissions") {
        cli_parts.push("--dangerously-skip-permissions".to_string());
    }
    if profile.experimental_agent_teams && !profile.extra_cli_args.contains("--teammate-mode") {
        cli_parts.push("--teammate-mode tmux".to_string());
    }
    if !profile.extra_cli_args.is_empty() {
        cli_parts.push(profile.extra_cli_args.trim().to_string());
    }
    let cli_suffix = if cli_parts.is_empty() {
        String::new()
    } else {
        format!(" {}", cli_parts.join(" "))
    };

    format!(
        "#!/bin/bash\n{}\n# Project: {}\n\ncd \"$(dirname \"$0\")\" || exit 1\n{} claude{}\n",
        SCRIPT_HEADER, safe_name, env_inline, cli_suffix
    )
}

/// Write the launch script to a project directory
pub fn write_script(
    project_path: &Path,
    project_name: &str,
    profile: &OptimizationProfile,
) -> Result<(), String> {
    let script_path = project_path.join("start-claude.sh");
    let content = generate_script(project_name, profile);

    fs::write(&script_path, &content)
        .map_err(|e| format!("Failed to write start-claude.sh: {}", e))?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = fs::Permissions::from_mode(0o755);
        fs::set_permissions(&script_path, perms)
            .map_err(|e| format!("Failed to chmod start-claude.sh: {}", e))?;
    }

    Ok(())
}

/// Remove the launch script from a project directory
pub fn remove_script(project_path: &Path) -> Result<(), String> {
    let script_path = project_path.join("start-claude.sh");
    if script_path.exists() {
        fs::remove_file(&script_path)
            .map_err(|e| format!("Failed to remove start-claude.sh: {}", e))?;
    }
    Ok(())
}

/// Read the launch script content
pub fn read_script(project_path: &Path) -> Result<String, String> {
    let script_path = project_path.join("start-claude.sh");
    fs::read_to_string(&script_path)
        .map_err(|e| format!("Failed to read start-claude.sh: {}", e))
}

/// List projects with launch script info
pub fn list_projects_with_launch_info(
    projects: Vec<crate::state::ProjectInfo>,
) -> Vec<ProjectWithLaunchScript> {
    projects
        .into_iter()
        .map(|p| {
            let project_path = Path::new(&p.path);
            let script_path = project_path.join("start-claude.sh");
            ProjectWithLaunchScript {
                name: p.name,
                path: p.path.clone(),
                encoded_name: p.encoded_name,
                has_launch_script: has_launch_script(project_path),
                launch_script_path: script_path.to_string_lossy().to_string(),
            }
        })
        .collect()
}
